--1. 脚本监控。
CREATE TABLE SUP_MON_SCRIPT
(
  ERROR_CODE       VARCHAR(100),
  TYPE             VARCHAR(100),
  MONITOR_CONTENT  VARCHAR(100),
  SCRIPT           VARCHAR(500),
  COMPAREPARAM     VARCHAR(500),
  WARN_INTERVAL    INT,
  WARN_MSG         VARCHAR(100),
  REMARK           VARCHAR(500),
  PHONES           VARCHAR(500),
    ENABLE           INT,
    PRIMARY KEY(ERROR_CODE)
)DEFAULT CHARSET=UTF8

--2. MQ监控。
CREATE TABLE XXT.SUP_MON_MQ
(
  ERROR_CODE       VARCHAR(100),
  ACCOUNT          VARCHAR(100),
  PASSWORD         VARCHAR(100),
  HOST             VARCHAR(100),
  PORT             INT,
  MONITOR_CONTENT  VARCHAR(100),
  QUEUE_NAMES      VARCHAR(500),
  COMPAREPARAM     VARCHAR(500),
  WARN_INTERVAL    INT,
  WARN_MSG         VARCHAR(100),
  REMARK           VARCHAR(1000),
  PHONES           VARCHAR(500),
  ENABLE           INT,
  PRIMARY KEY(ERROR_CODE)
)DEFAULT CHARSET=UTF8


--3. Url监控。
CREATE TABLE SUP_MON_URL
(
  ERROR_CODE       VARCHAR(100),
  TYPE             VARCHAR(100),
  MONITOR_CONTENT  VARCHAR(100),
  URL                              VARCHAR(500),
  COMPAREPARAM     VARCHAR(500),
  WARN_INTERVAL    INT,
  WARN_MSG         VARCHAR(100),
  REMARK           VARCHAR(1000),
  PHONES           VARCHAR(500),
  ENABLE           INT
)DEFAULT CHARSET=UTF8
Insert into XXT.SUP_MON_url
   (TYPE, MONITOR_CONTENT, url, COMPAREPARAM, WARN_INTERVAL, 
    WARN_MSG, PHONES, ENABLE)
 Values
   ('mon', '1', 'www.baidu.com', '>', 100, 
    'url 测试', '13512719456,15917241380,13590928109', 1);

--4. 数据库监控。
CREATE TABLE SUP_MON_SQL
(
  ERROR_CODE       VARCHAR(100),
  TYPE             VARCHAR(100),
  MONITOR_CONTENT  VARCHAR(100),
  SQL              VARCHAR(500),
  COMPAREPARAM     VARCHAR(500),
  WARN_INTERVAL    INT,
  WARN_MSG         VARCHAR(100),
  REMARK           VARCHAR(500),
  PHONES           VARCHAR(500),
  ENABLE           INT,
  PRIMARY KEY(ERROR_CODE)
)DEFAULT CHARSET=UTF8

--5. REDIS监控。
CREATE TABLE SUP_MON_REDIS
(
  ERROR_CODE       VARCHAR(100),
  TYPE             VARCHAR(100),
  MONITOR_CONTENT  VARCHAR(100),
  MONITOR_KEY      VARCHAR(500),
  HOST			   VARCHAR(500),
  PORT			   INT,
  PWD              VARCHAR(500),
  CONN_TIME_OUT	   INT,
  COMPAREPARAM     VARCHAR(500),
  WARN_INTERVAL    INT,
  WARN_MSG         VARCHAR(100),
  REMARK           VARCHAR(500),
  PHONES           VARCHAR(500),
  ENABLE           INT,
  PRIMARY KEY(ERROR_CODE)
)DEFAULT CHARSET=UTF8

